# The first instruction is what image we want to base our container on
# We Use an official Python runtime as a parent image
FROM python:3.9.7-slim

# The enviroment variable ensures that the python output is set straight
# to the terminal with out buffering it first
ENV PYTHONUNBUFFERED 1

# create root directory for our project in the container
RUN mkdir /app

# Set the working directory to /app
WORKDIR /app

# create virtual enviroment in docker container 
RUN python3 -m  venv /opt/venv

# create virtual enviroment in docker container 
# COPY requirements.txt ./

# upgrade pip to recent version in docker container 
RUN pip install pip --upgrade

# install all libraries and dependencies into the docker container
RUN /opt/venv/bin/pip install -r requirements.txt

# Copy the current directory contents into the container at app
ADD . /app/

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

RUN chmod +x entrypoint.sh

CMD [ "/app/entrypoint.sh" ]