# Generated by Django 4.1.4 on 2023-07-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.CharField(default='ZSlmEHXspH7NHr6', editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
