# Generated by Django 4.1.4 on 2023-07-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_wishlist_review_recent_deliveryinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='recent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='DeliveryInfo',
        ),
        migrations.DeleteModel(
            name='Recent',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
