# Generated by Django 5.2.17 on 2026-10-03 13:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_digital_fulfillment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Shipping weight in pounds (lbs).', max_digits=6),
        ),
    ]
