# Generated by Django 4.1.4 on 2026-10-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash_sale_end',
            field=models.DateTimeField(blank=True, help_text='Optional expiration timestamp for limited-time flash deals.', null=True),
        ),
    ]
