# Generated by Django 4.1.4 on 2026-10-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_flash_sale_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.JSONField(blank=True, default=list, help_text='List of product variant options (e.g. size, color, stock, price delta).'),
        ),
    ]
