# Generated by Django 4.1.4 on 2023-08-01 01:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=110)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "discount",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ]
                    ),
                ),
                (
                    "available",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FSHN", "fishing"),
                            ("SPRT", "sports"),
                            ("ELCT", "electronics"),
                            ("PHNS", "phones"),
                            ("GMES", "games"),
                            ("TBLT", "tablets"),
                            ("OUWR", "outwear"),
                            ("PETS", "pets"),
                            ("TOYS", "toys"),
                            ("CMPT", "computing"),
                            ("LNGR", "lingerie"),
                            ("BOOK", "books"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("NEW", "new"),
                            ("", "none"),
                            ("BTS", "bestseller"),
                            ("SDT", "sold out"),
                        ],
                        default="NEW",
                        max_length=50,
                    ),
                ),
                ("visibility", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="images"
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("usps_delivery_date", models.IntegerField(default=0)),
                (
                    "usps_service",
                    models.CharField(
                        choices=[
                            ("express", "none"),
                            ("priority", "new"),
                            ("firstclass", "bestseller"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sponsored", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=4)),
                ("height", models.DecimalField(decimal_places=2, max_digits=4)),
                ("width", models.DecimalField(decimal_places=2, max_digits=4)),
                ("breadth", models.DecimalField(decimal_places=2, max_digits=4)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="images"
                    ),
                ),
                (
                    "productId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
