# Generated by Django 5.0.6 on 2024-06-08 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('available', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('fishing', 'fishing'), ('sports', 'sports'), ('electronics', 'electronics'), ('phones', 'phones'), ('games', 'games'), ('tablets', 'tablets'), ('outwear', 'outwear'), ('pets', 'pets'), ('toys', 'toys'), ('computing', 'computing'), ('lingerie', 'lingerie'), ('books', 'books'), ('beverages', 'beverages')], max_length=15)),
                ('label', models.CharField(choices=[('new', 'new'), ('', 'none'), ('bestseller', 'bestseller'), ('sold out', 'sold out')], default='NEW', max_length=50)),
                ('visibility', models.BooleanField(default=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('sales', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sponsored', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('serial', models.CharField(max_length=25, unique=True)),
                ('attributes', models.CharField(max_length=250)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('width', models.DecimalField(decimal_places=2, max_digits=4)),
                ('breadth', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('color', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
