# Generated by Django 4.1.4 on 2023-07-25 13:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("affiliates", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Affiliate",
            new_name="Marketer",
        ),
    ]
