# Generated by Django 4.1.4 on 2023-08-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketer",
            name="marketer_id",
            field=models.CharField(
                default="tomeMRdGWxDU1-J", editable=False, max_length=70, unique=True
            ),
        ),
    ]
