# Generated by Django 4.1.4 on 2023-08-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0003_alter_marketer_marketer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketer",
            name="marketer_id",
            field=models.CharField(
                default="zHAv8lfh13wT4hN", editable=False, max_length=70, unique=True
            ),
        ),
    ]
