# Generated by Django 4.1.4 on 2023-07-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0004_alter_marketer_marketer_id_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketer",
            name="marketer_id",
            field=models.CharField(
                default="12a3d5826724", editable=False, max_length=70, unique=True
            ),
        ),
    ]
