# Generated by Django 4.1.4 on 2023-07-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0008_alter_marketer_marketer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketer",
            name="marketer_id",
            field=models.CharField(
                default="3e2b8342fdd1", editable=False, max_length=70, unique=True
            ),
        ),
    ]
