# Generated by Django 4.1.4 on 2023-10-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(default='wcL7FefMYajbIKX', editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
