# Generated by Django 5.0.6 on 2024-06-08 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliates', '0002_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='redirect',
            name='urlId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliates.url'),
        ),
    ]
