# Generated by Codex on 2026-09-30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliates", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketer",
            name="marketer_id",
            field=models.CharField(editable=False, max_length=70, unique=True),
        ),
        migrations.CreateModel(
            name="AffiliateWallet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("balance", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="affiliate_wallet", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AffiliateWalletTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("transaction_type", models.CharField(choices=[("credit", "Credit"), ("debit", "Debit")], max_length=10)),
                ("reason", models.CharField(max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="affiliates.affiliatewallet")),
            ],
            options={
                "ordering": ["-created", "-pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("reward_amount", models.DecimalField(decimal_places=2, default=Decimal("25.00"), max_digits=12)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("rewarded", "Rewarded")], default="pending", max_length=20)),
                ("marketer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="referrals", to="affiliates.marketer")),
                ("referred_user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="affiliate_referral", to=settings.AUTH_USER_MODEL)),
                ("wallet_transaction", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="referral", to="affiliates.affiliatewallettransaction")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="referral",
            constraint=models.UniqueConstraint(fields=("marketer", "referred_user"), name="unique_marketer_referred_user"),
        ),
    ]
