# containers
apiVersion: v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          command: ["nginx"]
          args: ["-p", "/etc/nginx/", "-c", "nginx.conf", "-g", "daemon off;"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-security
              mountPath: /etc/nginx
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
      volumes:
        - name: nginx-security
          configMap:
            name: nginx-security

---


# Load-balancer
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: nginx-deployment



---


# cron-jobs
# will set up correctly 
apiVersion: v1
kind: CronJob
metadata:
  name: helloworld
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: task
              image: busybox
              command:
                - /bin/sh
                - -c
                - date; echo 'Hello World from Cronitor.io';
