apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
configMapGenerator:
  - name: nginx-security
    files:
      - nginx.conf
      - upstream.conf
      - blocked-ips.conf
      - suspected-ips.conf
      - allowed-ips.conf
      - trusted-proxies.conf
