# Generated by Django 5.0.6 on 2024-06-08 15:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField()),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('num_available', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('num_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('pick up', 'pick up'), ('home delivery', 'home delivery')], max_length=150)),
                ('total', models.IntegerField(default=0)),
                ('delivery_type', models.CharField(choices=[('priority', 'new'), ('express', 'none'), ('firstclass', 'bestseller')], max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('orderId', models.CharField(default='hiIr3OkNz8r80', editable=False, max_length=15, unique=True)),
                ('coupon_code', models.CharField(max_length=50)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('cancelled', 'cancelled'), ('refunded', 'refunded'), ('delivered', 'delivered'), ('shipped', 'shipped'), ('picked up', 'picked up'), ('confirmed', 'confirmed')], max_length=15)),
                ('ordered', models.BooleanField(default=False)),
                ('payment_type', models.CharField(default='card', max_length=30)),
                ('ordered_date', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('successful', 'successful'), ('failed', 'failed')], default='pending', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryEstimates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('usps_service', models.CharField(choices=[('priority', 'new'), ('express', 'none'), ('firstclass', 'bestseller')], max_length=20)),
                ('usps_delivery_date', models.IntegerField(default=0)),
                ('pick_up', models.IntegerField(default=25)),
                ('standard_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('express_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('destination_zip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
