# Generated by Django 4.1.4 on 2023-10-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.CharField(default='PiUfb1s1fYplf', editable=False, max_length=15, unique=True),
        ),
    ]
