# Generated by Django 4.1.4 on 2023-08-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="orderId",
            field=models.CharField(
                default="tKvOVHQkmH", editable=False, max_length=15, unique=True
            ),
        ),
    ]
