# Generated by Django 4.1.4 on 2023-08-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_alter_order_orderid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="orderId",
            field=models.CharField(
                default="IyX5lusmE4y3e", editable=False, max_length=15, unique=True
            ),
        ),
    ]
