"""
Django settings for codematics project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
from urllib.parse import urlsplit
import dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOCAL_ENV_FILE = BASE_DIR / '.env'
if LOCAL_ENV_FILE.is_file():
    if hasattr(dotenv, "read_dotenv"):
        dotenv.read_dotenv(str(LOCAL_ENV_FILE))
    elif hasattr(dotenv, "load_dotenv"):
        dotenv.load_dotenv(str(LOCAL_ENV_FILE))
SETTINGS_PATH = os.path.dirname(os.path.dirname(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = str(os.environ.get("SECRET_KEY"))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

ENV_ALLOWED_HOST = str(os.environ.get("ENV_ALLOWED_HOST"))
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
if ENV_ALLOWED_HOST:
    ALLOWED_HOSTS = [ ENV_ALLOWED_HOST ]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "notification.apps.EventNotificationConfig",
    "observability.apps.ObservabilityConfig",
    "core.apps.CoreConfig",
    "product.apps.ProductConfig",
    "store.apps.StoreConfig",
    "staff.apps.StaffConfig",
    "payment.apps.PaymentConfig",
    "affiliates.apps.AffiliatesConfig",
    "cart.apps.CartConfig",


    "django_filters",
    "corsheaders",
    "rest_framework",
    'django_user_agents',
    "phonenumber_field",
    "push_notifications",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "taggit",
    "stripe",
    "rest_framework_word_filter",
    "dotenv",
    'silk',
    'django_elasticsearch_dsl',
    'django_cleanup.apps.CleanupConfig',

]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    'silk.middleware.SilkyMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django_user_agents.middleware.UserAgentMiddleware',
]

ROOT_URLCONF = "codematics.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(SETTINGS_PATH, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "codematics.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


DATABASE_ENGINE = os.environ.get("DATABASE_ENGINE", "sqlite").lower()
DATABASE_PATH = os.environ.get("SQLITE_DATABASE_PATH") or os.path.join(BASE_DIR, "main.sqlite3")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DATABASE_PATH,
    }
}

DB_USERNAME = os.environ.get("POSTGRES_USER")
DB_PASSWORD = os.environ.get("POSTGRES_PASSWORD")
DB_DATABASE = os.environ.get("POSTGRES_DB")
DB_HOST = os.environ.get("POSTGRES_HOST")
DB_PORT = os.environ.get("POSTGRES_PORT", "5432")
DB_IS_AVAIL = all([DB_USERNAME, DB_PASSWORD, DB_DATABASE, DB_HOST, DB_PORT])
DB_REQUIRE_SSL = os.environ.get("DB_REQUIRE_SSL", "false").lower() == "true"

if DATABASE_ENGINE in {"postgres", "postgresql"}:
    if not DB_IS_AVAIL:
        raise RuntimeError("PostgreSQL requires POSTGRES_HOST, POSTGRES_DB, POSTGRES_USER, and POSTGRES_PASSWORD.")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": DB_DATABASE,
            "USER": DB_USERNAME,
            "PASSWORD": DB_PASSWORD,
            "HOST": DB_HOST,
            "PORT": DB_PORT,
            "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", "60")),
            "CONN_HEALTH_CHECKS": True,
        }
    }
    if DB_REQUIRE_SSL:
        DATABASES["default"]["OPTIONS"] = {"sslmode": "require"}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# to change default timezone to that of user
# USE_L10N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Object storage is optional locally. Production can enable any S3-compatible
# provider through the same django-storages settings below.
OBJECT_STORAGE_ENABLED = os.environ.get('OBJECT_STORAGE_ENABLED', 'true').lower() == 'true'
MINIO_ENDPOINT_URL = os.environ.get('MINIO_ENDPOINT_URL', 'http://127.0.0.1:9000')
MINIO_PUBLIC_URL = os.environ.get('MINIO_PUBLIC_URL', MINIO_ENDPOINT_URL).rstrip('/')
MINIO_BUCKET_NAME = os.environ.get('MINIO_BUCKET_NAME', 'commerce-images')
_media_endpoint = urlsplit(MINIO_PUBLIC_URL)
STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'access_key': os.environ.get('MINIO_ACCESS_KEY', ''),
            'secret_key': os.environ.get('MINIO_SECRET_KEY', ''),
            'bucket_name': MINIO_BUCKET_NAME,
            'endpoint_url': MINIO_ENDPOINT_URL,
            'region_name': os.environ.get('MINIO_REGION', 'us-east-1'),
            'signature_version': 's3v4',
            'addressing_style': 'path',
            'default_acl': None,
            'file_overwrite': False,
            'querystring_auth': False,
            'custom_domain': f'{_media_endpoint.netloc}{_media_endpoint.path}/{MINIO_BUCKET_NAME}',
            'url_protocol': f'{_media_endpoint.scheme}:',
        },
    },
    'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
}
if OBJECT_STORAGE_ENABLED:
    MEDIA_URL = f'{MINIO_PUBLIC_URL}/{MINIO_BUCKET_NAME}/'
else:
    STORAGES['default'] = {'BACKEND': 'django.core.files.storage.FileSystemStorage'}
    MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "core.User"

CACHE_URL = os.environ.get("CACHE_URL") or os.environ.get("REDIS_URL")
CACHE_TIMEOUT = int(os.environ.get("CACHE_TIMEOUT", 60 * 5))
CACHE_MAX_ENTRIES = int(os.environ.get("CACHE_MAX_ENTRIES", 256))

if CACHE_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": CACHE_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "IGNORE_EXCEPTIONS": True,
                "SOCKET_CONNECT_TIMEOUT": 2,
                "SOCKET_TIMEOUT": 2,
            },
            "KEY_PREFIX": os.environ.get("CACHE_KEY_PREFIX", "codematics"),
            "TIMEOUT": CACHE_TIMEOUT,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "codematics-cache",
            "TIMEOUT": CACHE_TIMEOUT,
            "OPTIONS": {
                "MAX_ENTRIES": CACHE_MAX_ENTRIES,
                "CULL_FREQUENCY": 3,
            },
        }
    }


ELASTICSEARCH_ENABLED = os.environ.get("ELASTICSEARCH_ENABLED", "false").lower() == "true"
ELASTICSEARCH_URL = os.environ.get("ELASTICSEARCH_URL", "http://127.0.0.1:9200")
ELASTICSEARCH_INDEX_PREFIX = os.environ.get("ELASTICSEARCH_INDEX_PREFIX", "commerce")
ELASTICSEARCH_PRODUCTS_INDEX = os.environ.get(
    "ELASTICSEARCH_PRODUCTS_INDEX",
    f"{ELASTICSEARCH_INDEX_PREFIX}-products",
)
ELASTICSEARCH_TIMEOUT = float(os.environ.get("ELASTICSEARCH_TIMEOUT", "2"))

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "http://localhost:3000",
    "http://127.0.0.1:3000",

]


REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    "EXCEPTION_HANDLER": "utils.exceptions.custom_exception_handler",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 15,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.environ.get("DRF_ANON_THROTTLE_RATE", "100/hour"),
        "user": os.environ.get("DRF_USER_THROTTLE_RATE", "1000/hour"),
        "auth": os.environ.get("DRF_AUTH_THROTTLE_RATE", "10/minute"),
    },
}

LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(levelname)s %(asctime)s %(name)s %(message)s"
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "loggers": {
        "codematics": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "codematics.api": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=3),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}


EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() == "true"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "Proace <hello@proace.example>",
)
APPLICATION_EMAIL = os.environ.get("APPLICATION_EMAIL", DEFAULT_FROM_EMAIL)
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "amqp://guest:guest@127.0.0.1:5672//")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "rpc://")
CELERY_TASK_DEFAULT_QUEUE = "commerce.notifications"
CELERY_BROKER_URL = os.environ.get(
    "CELERY_BROKER_URL",
    "redis://127.0.0.1:6379/1",
)
CELERY_RESULT_BACKEND = None
CELERY_TASK_ROUTES = {
    "notification.tasks.deliver_notification_task": {
        "queue": CELERY_TASK_DEFAULT_QUEUE,
    },
    "notification.tasks.recover_notification_deliveries": {
        "queue": CELERY_TASK_DEFAULT_QUEUE,
    },
}
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_TIME_LIMIT = 120
CELERY_TASK_IGNORE_RESULT = True
CELERY_BEAT_SCHEDULE = {
    "recover-notification-deliveries": {
        "task": "notification.tasks.recover_notification_deliveries",
        "schedule": timedelta(seconds=60),
    },
}
NOTIFICATION_DELIVERY_MAX_ATTEMPTS = int(
    os.environ.get("NOTIFICATION_DELIVERY_MAX_ATTEMPTS", "8")
)
NOTIFICATION_DELIVERY_STALE_SECONDS = int(
    os.environ.get("NOTIFICATION_DELIVERY_STALE_SECONDS", "300")
)


PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
]

STRIPE_SECRET = str(os.environ.get("STRIPE_SECRET"))
PUBLISHER_KEY = str(os.environ.get("PUBLISHER_KEY"))


CRON_CLASSES = [
    "core.cron.set_product_visibility",
    "core.cron.deactivate_coupon"
]


TAGGIT_CASE_INSENSITIVE = True

SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_SSL_REDIRECT = False


USER_AGENTS_CACHE = 'default'
# AIRSHIP_KEY = str(os.environ.get("AIRSHIP_KEY"))
# MASTER_SECRET = str(os.environ.get("MASTER_SECRET"))

PUSH_NOTIFICATIONS_SETTINGS = {
    "FCM_API_KEY": str(os.environ.get("FCM_KEY")),
    "GCM_API_KEY": "[your api key]",
    "APNS_CERTIFICATE": "/path/to/your/certificate.pem",
}

SILKY_PYTHON_PROFILER = True
SILKY_PYTHON_PROFILER_BINARY = True


ELASTICSEARCH_DSL={
    'default': {
        'hosts': 'localhost:9200'
    },
}

from observability.config import configure as configure_observability
configure_observability(globals())
