# Generated by Django 5.2.17 on 2026-10-03 18:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_order_carrier_order_delivered_at_order_shipped_at_and_more'),
        ('store', '0007_store_is_official'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='storepayout',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='store.store'),
        ),
        migrations.CreateModel(
            name='MerchantWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('stripe_account_id', models.CharField(blank=True, default='', max_length=100)),
                ('stripe_details_submitted', models.BooleanField(default=False)),
                ('stripe_payouts_enabled', models.BooleanField(default=False)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='storepayout',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='store.merchantwallet'),
        ),
        migrations.CreateModel(
            name='StoreEarningsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('sale', 'Sale'), ('fee', 'Platform Fee'), ('payout', 'Payout'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], default='sale', max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('completed', 'Completed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('available_at', models.DateTimeField(blank=True, help_text='When escrow hold clears', null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_ledger_entries', to='payment.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='store.store')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='store.merchantwallet')),
            ],
            options={
                'ordering': ['-created', '-pk'],
            },
        ),
    ]
