# Generated by Django 4.1.4 on 2026-10-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_storeinfo_profile_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinfo',
            name='announcement',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='pinned_products',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
