# Generated by Django 4.1.4 on 2023-07-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_wishlist_review_recent_deliveryinfo_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.CharField(default='clhfrZJk78EDlHw', editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
