# Generated by Django 4.1.4 on 2023-07-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='recent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.CharField(default='8NWuqfiSkox0Cc0', editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='DeliveryInfo',
        ),
        migrations.DeleteModel(
            name='Recent',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
