# Generated by Django 4.1.4 on 2023-07-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_recent_productid_remove_recent_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.CharField(default='R2gMkjuq9IgmAcy', editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
