'use client';
import Link from 'next/link';
import { ArrowRight, Package, ShieldCheck, Truck } from 'lucide-react';
export function HelpPage() {
  return <div className="container help-page"><span className="eyebrow green">A LITTLE HELP GOES A LONG WAY</span><h1>Good questions.<br />Clear answers.</h1><div className="help-links"><Link href="/account/orders"><Package /><h3>Follow your order</h3><ArrowRight size={18} /></Link><Link href="/account/addresses"><Truck /><h3>Delivery addresses</h3><ArrowRight size={18} /></Link><Link href="/account/profile"><ShieldCheck /><h3>Your account</h3><ArrowRight size={18} /></Link></div><h2>The everyday questions</h2>{[['How much is delivery?', 'Delivery costs ₦2,500 per order. Orders of ₦100,000 or more qualify for free delivery. Your final delivery cost is shown before you place your order.'], ['How do I pay?', 'Cash on delivery is currently available. You will not be charged online when you place an order. Pay when your order arrives.'], ['When will my order arrive?', 'Delivery timing depends on your seller and location. Your order history shows confirmation, shipping and delivery status.'], ['Can I return an item?', 'Return eligibility depends on the seller and product. Keep your order reference and packaging, and confirm the seller’s return conditions before purchasing.'], ['Where can I find my orders?', 'Sign in and open My account, then My orders. Each order includes the items, delivery address, amount and current status.'], ['How do I start selling?', 'Open the seller workspace, create your store and add a pickup address. You can then create product drafts, add images and publish your listings.']].map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}<Link className="text-link" href="/shop">Back to discovering <ArrowRight size={16} /></Link></div>;
}
export function PolicyPage({ type }: { type: string }) {
  const privacy = type === 'privacy';
  return <article className="container policy-page"><span className="eyebrow green">GOOD TO KNOW</span><h1>{privacy ? 'Your privacy matters.' : 'Shopping with Proace.'}</h1>{privacy ? <><h2>Your account information</h2><p>Proace stores the account details you provide, including your name, email and phone number. Your delivery addresses and orders are associated with your account. Passwords are stored as hashes, not readable text.</p><h2>Cookies and saved finds</h2><p>Essential cookies keep you signed in. Your browser stores guest shopping bags and saved items locally. Signing in adds eligible guest items to your account.</p><h2>Orders and sellers</h2><p>Order information supports fulfillment. Merchant order views are restricted to the products belonging to that seller. External product photographs may be loaded from the image providers chosen by sellers.</p><h2>Your choices</h2><p>You can update your personal details, remove saved addresses and sign out from your account. Only enter information necessary for your purchase.</p></> : <><h2>Products and availability</h2><p>Product descriptions, prices and availability are provided by sellers. Stock is checked again when you place an order. Adding an item to your bag does not reserve it.</p><h2>Pricing and payment</h2><p>Prices are displayed in Nigerian naira. The checkout total includes the delivery cost shown before confirmation. Cash-on-delivery orders are payable when delivered; placing an order does not collect an online payment.</p><h2>Delivery</h2><p>Delivery costs ₦2,500, with free delivery for orders of ₦100,000 or more. Timing depends on the seller and destination. Check that your delivery address is complete and correct before ordering.</p><h2>Returns and order questions</h2><p>Return conditions vary by seller and item. Confirm eligibility before purchasing and retain your order reference and packaging. Do not return an item without arranging it with the seller.</p></>}<Link className="text-link" href="/help">Visit the help centre <ArrowRight size={16} /></Link></article>;
}
