'use client';
import Link from 'next/link';
import { ArrowRight, Package, ShieldCheck, Truck } from 'lucide-react';
import { business, contactLinks } from '@/lib/business';
export function HelpPage() {
  return <div className="container help-page"><span className="eyebrow green">A LITTLE HELP GOES A LONG WAY</span><h1>Good questions.<br />Clear answers.</h1><p>Customer support is available {business.supportSchedule}. Email <a href={contactLinks.supportEmail}>{business.supportEmail}</a> or message us on <a href={contactLinks.whatsapp} target="_blank" rel="noreferrer">WhatsApp at {business.whatsapp}</a>.</p><div className="help-links"><Link href="/account/orders"><Package /><h3>Follow your order</h3><ArrowRight size={18} /></Link><Link href="/account/addresses"><Truck /><h3>Delivery addresses</h3><ArrowRight size={18} /></Link><Link href="/account/profile"><ShieldCheck /><h3>Your account</h3><ArrowRight size={18} /></Link></div><h2>The everyday questions</h2>{[['How much is delivery?', 'Digital products have no shipping fee and are generally delivered immediately. Physical-product shipping depends on the provider, destination, weight and package size. The applicable charge is shown during checkout.'], ['How do I pay?', `We accept ${business.paymentMethods}. Available options may vary by country and payment processor.`], ['When will my order arrive?', 'Digital products are generally available immediately. Physical-product delivery timing depends on the provider and destination; tracking and status updates appear in your order history when available.'], ['Can I cancel an order?', 'Cancellation requests must be made within 12 hours of placing the order. Contact order support as soon as possible; fulfilled or downloaded orders may no longer be cancellable.'], ['Can I return an item?', 'Return eligibility and the return period depend on the seller and product. Approved refunds are normally processed within 3–7 days after the returned product is received and inspected for damage.'], ['Can I refund a digital product?', 'Digital-product refund eligibility is reviewed case by case and may depend on whether the product has already been accessed or downloaded.'], ['Where can I find my orders?', 'Sign in and open My account, then My orders. Each order includes its items, delivery details, amount and current status.'], ['How do I start selling?', 'Open the seller workspace, create your store and add a pickup address. You can then create product drafts, add images and publish your listings.']].map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}<p>Order questions: <a href={contactLinks.orderEmail}>{business.orderEmail}</a><br />Seller support: <a href={contactLinks.sellerEmail}>{business.sellerEmail}</a></p><Link className="text-link" href="/shop">Back to discovering <ArrowRight size={16} /></Link></div>;
}
export function PolicyPage({ type }: { type: string }) {
  const privacy = type === 'privacy';
  return <article className="container policy-page"><span className="eyebrow green">GOOD TO KNOW</span><h1>{privacy ? 'Your privacy matters.' : 'Shopping with ProAce.'}</h1>{privacy ? <><h2>Your account information</h2><p>{business.legalName} stores the account details you provide, including your name, email and phone number. Delivery addresses and orders are associated with your account. Passwords are stored as secure hashes rather than readable text.</p><h2>Cookies and saved finds</h2><p>Essential cookies keep you signed in. Your browser stores guest shopping bags and saved items locally. Signing in adds eligible guest items to your account.</p><h2>Orders, sellers and processors</h2><p>Order information is shared as necessary for fulfillment. Seller access is restricted to relevant orders and products. Payment processors handle payment information under their own privacy and security terms.</p><h2>Your choices</h2><p>You can update your personal details, remove saved addresses and sign out. For privacy questions or requests, email <a href={`mailto:${business.privacyEmail}`}>{business.privacyEmail}</a>.</p></> : <><h2>Company and service area</h2><p>{business.legalName} is based in {business.location} and serves an international audience. Prices are displayed in US dollars; payment processors may offer currency conversion.</p><h2>Products and availability</h2><p>Descriptions, prices and availability are provided by sellers. Stock is checked when an order is placed, and adding an item to a bag does not reserve it.</p><h2>Payment</h2><p>Accepted methods include {business.paymentMethods}. The options available at checkout may depend on the customer’s country and the payment processor.</p><h2>Delivery</h2><p>Digital products have no shipping fee and are generally delivered immediately. Physical-product charges and timing depend on the provider, destination, weight and package size. ProAce does not currently calculate customs or import duties; destination or provider requirements may still apply.</p><h2>Cancellations, returns and refunds</h2><p>Cancellation requests must be submitted within 12 hours. Return eligibility and return periods depend on the product and seller. Approved refunds are normally processed 3–7 days after a returned item is received and inspected. Digital refunds are reviewed case by case, including whether access or download has occurred.</p><h2>Questions</h2><p>Email <a href={contactLinks.orderEmail}>{business.orderEmail}</a> for order assistance or <a href={`mailto:${business.legalEmail}`}>{business.legalEmail}</a> for legal questions.</p></>}<Link className="text-link" href="/help">Visit the help centre <ArrowRight size={16} /></Link></article>;
}
